services:
  grafana:
    user: root
    container_name: 'dartsisas-shaperenderer-panel'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.5.3}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
    volumes:
      - ../dist:/var/lib/grafana/plugins/dartsisas-shaperenderer-panel
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/dartsisas-shaperenderer-panel

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.dartsisas-shaperenderer-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: dartsisas-shaperenderer-panel
